### ISSUE TITLE
Why is pypandoc a build requirement?

### ISSUE THREAD

**Issue by robin-snt** [dgraph-io/pydgraph#82]
This line is now causing errors in the build process of the software I manage that has `pydgraph` as a dependency!

I'm wondering if there's something I can change on my end or if I need to request a change to your `setup.py` file.

On my end I'm doing:

```sh
devpi upload --no-vcs --formats=bdist_wheel
```
This seems to trigger the code in the `setup.py` of pydgraph.
Is it possible for you to correctly format your code without causing errors for users of your package?

**Comment by martinmr** [comment]
Fixed by #81

**Comment by robin-snt** [comment]
Can you please reopen this issue, as #81 only solves the compatibility issue with Python 3.6+. The check on `sys.argv` (https://github.com/dgraph-io/pydgraph/blob/3fab5e2a2807fc57cb9cf88d71c13ca444fa687f/setup.py#L27) makes the problem persist whenever I want to build my own package with `bdist_wheel` and my package has `pydgraph` as its dependency.

**Comment by martinmr** [comment]
ok. I'll remove this if statement entirely since it's not doing anything very important. Expect a new release today.

**Comment by martinmr** [comment]
Just released pydgraph 2.0.2 which does not throw errors when pypandoc is not found.
